stages:
  - build
  - deploy

build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  only:
    - master

deploy:
  image:
    name: dtzar/helm-kubectl:3.0.1
  stage: deploy
  environment:
    name: prod
    url: https://corona.psota.pl
  script:
    - helm upgrade --install corona --timeout=3600s --namespace corona --set image.tag="$CI_COMMIT_SHA" charts/corona
  only:
    - master
